BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: 'Input miles'
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.2
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert miles to km'
    Label:
        text: '54'
        color: (1, 1, 0, 1)